alter table coachings
  add column result_overall_strength_text text;

create table coaching_feedback_cards (
  id bigint generated by default as identity primary key,
  coaching_id bigint not null,
  card_order int not null,
  display_order int not null,
  title text,
  cause text,
  expected_effect text,

  constraint fk_coaching_feedback_cards_coaching
    foreign key (coaching_id) references coachings(id) on delete cascade,

  constraint uq_coaching_feedback_cards_order
    unique (coaching_id, card_order)
);

create table coaching_feedback_observations (
  id bigint generated by default as identity primary key,
  feedback_card_id bigint not null,
  observation_order int not null,
  timecode text,
  text text not null,

  constraint fk_coaching_feedback_observations_card
    foreign key (feedback_card_id) references coaching_feedback_cards(id) on delete cascade,

  constraint uq_coaching_feedback_observations_order
    unique (feedback_card_id, observation_order)
);

create table coaching_practice_steps (
  feedback_card_id bigint not null,
  step_order int not null,
  text text not null,

  constraint pk_coaching_practice_steps
    primary key (feedback_card_id, step_order),

  constraint fk_coaching_practice_steps_card
    foreign key (feedback_card_id) references coaching_feedback_cards(id) on delete cascade
);
