create table coachings (
  id bigint generated by default as identity primary key,

  status text not null,

  video_original_filename text,
  video_content_type text,
  video_size_bytes bigint,

  performance_intent text not null,

  ai_provider text,
  ai_model text,
  ai_temperature decimal(4, 2),
  ai_prompt_version text,

  result_scene_intent text,
  result_scene_intent_source text,

  result_strength_timecode text,
  result_strength_axis text,
  result_strength_signal text,
  result_strength_why text,
  result_strength_tier text,

  result_focus_timecode text,
  result_focus_axes json,
  result_focus_observed_signal text,
  result_focus_root_cause text,
  result_focus_intent_gap text,
  result_focus_prescription text,

  result_next_step_text text,
  result_next_step_action text,

  failure_code text,
  failure_message text,

  created_at timestamp(6) with time zone not null,
  updated_at timestamp(6) with time zone not null,
  completed_at timestamp(6) with time zone
);
